### ISSUE TITLE
Use Connector instead of Traces->Logs hack

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#1803]
In the current implementation we use the following pipelines to convert traces to logs:
```yaml
service:
  pipelines:
    logs/fake:
      receivers: ["filelog"]
      exporters: ["otlp/loopback"]
    traces:
      receivers: ["otlp"]
      processors: ["tracestologs"]
      exporters: ["logging"]
```

As OTLP has introduced [Connectors](https://github.com/open-telemetry/opentelemetry-collector/tree/main/connector), this is the perfect tool to replace the above hack.

The goal of this ticket is to rewrite `tracestologs` from being processor to being connector.
