### ISSUE TITLE
Allow providing api key to aperturectl via env or file

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#2402]
Initial proposal:
* ~~Add `APERTURECTL_API_KEY` that stores _path_ to the file which contains controller's api key.~~
* If that flag is present, we change the default of connecting to `--kube` to connect to production cloud controller using that api key (no `--controller` flag is necessary).
* We also need some kind of way to use that env variable with different address of controller than production (for internal testing). We don't need to document it though.

**Comment by krdln** [comment]
This is my understanding of what we've agreed on:

Config file (toml or ini or json whatever you choose. I like toml, but I'm ok with others), something like:

```toml
[controller]
api-key = "xxx" // perhaps call it `token`, not api key? Lot of places call it token, eg. github, crates.io, etc.
address = "org.fluxninja.com" // or perhaps just organization and we can create ctrl addr from it?
```

Config file default location: `~/.aperturectl/config` or `~/.aperturectl/config.toml` – not sure if we should include extension or not :shrug: 

Config file env variable `APERTURECTL_CONFIG`

Config file flag for aperturectl `--config CONFIG_PATH`.

Precedence:
1. command line (`--kube`, `--controller`, `--api-key`)
2. Config from `--config PATH`
3. Config from env
4. Config from default location

Note: configs don't merge, we load one config.

If there's no config file, we default to `--kube`.

Optionally we can implement this opentelemetry style syntax for interpolating env variables which would work for cmdline args, although I think that with config files, that's too much possible solutions.
