### ISSUE TITLE
[Controller] Crash after creating and then retrieving empty policy

### ISSUE THREAD

**Issue by alexander-falca** [fluxninja/aperture#2525]
**Describe the bug**
Controller fails with empty policies

**Steps to reproduce**
1/ Start controller
2/ Create an empty policy via REST API using payload: 
```json
{
    "policy": {}
}
```
3/ Read policy via REST GET API

**What did you expect to see?**
At least empty policy returned or validation errors on create

**What did you see instead?**
Controller crashed with following error
```

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xc000c3ad50 addr=0x35b4e20 pc=0x34e45e3]

goroutine 370 [running]:
github.com/fluxninja/aperture/v2/pkg/panic-handler.(*PanicHandlerRegistry).Crash(0xc000d6d6e0, {0x3c7b280, 0x712b590})
	/src/pkg/panic-handler/panic-handler.go:95 +0x92
github.com/fluxninja/aperture/v2/pkg/panic-handler.(*PanicHandlerRegistry).Go.func1.1()
	/src/pkg/panic-handler/panic-handler.go:105 +0x3c
panic({0x3c7b280, 0x712b590})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/fluxninja/aperture/v2/pkg/policies/controlplane/circuitfactory.(*Circuit).Components(...)
	/src/pkg/policies/controlplane/circuitfactory/circuit.go:21
github.com/fluxninja/aperture/v2/pkg/policies/controlplane.newPolicyOptions(0x1c?, {0x4da4cb0?, 0xc001390c00?})
	/src/pkg/policies/controlplane/policy.go:65 +0x263
github.com/fluxninja/aperture/v2/pkg/policies/controlplane.(*PolicyFactory).provideControllerPolicyFxOptions(0xc0009293b0, {0x4d4efc0?, 0xc0003dda00?}, {0x4d90a40, 0xc0003dd4c0}, {0x4da4cb0, 0xc001390c00})
	/src/pkg/policies/controlplane/policy-factory.go:158 +0x16d
github.com/fluxninja/aperture/v2/pkg/notifiers.(*fxRunner).initApp(0xc000846f00, {0xc00138ee39, 0x4}, {0x4d90a40?, 0xc0003dd4c0})
	/src/pkg/notifiers/fx-driver.go:65 +0x243
github.com/fluxninja/aperture/v2/pkg/notifiers.(*fxRunner).processEvent(0xc000846f00, {{0xc00138ee39, 0x4}, {0xc000df4bd0, 0x6e, 0x70}, 0x1}, {0x4d90a40, 0xc0003dd4c0})
	/src/pkg/notifiers/fx-driver.go:43 +0x29a
github.com/fluxninja/aperture/v2/pkg/notifiers.(*unmarshalKeyNotifier).Notify(0xc000bef4a0?, {{0xc00138ee39, 0x4}, {0xc000df4bd0, 0x6e, 0x70}, 0x1})
	/src/pkg/notifiers/unmarshal-notifier.go:54 +0x111
github.com/fluxninja/aperture/v2/pkg/notifiers.transformNotify({0x4d944d0, 0xc000846f00}, {{0xc00138ee39, 0x4}, {0xc000df4bd0, 0x6e, 0x70}, 0x1})
	/src/pkg/notifiers/notifier.go:118 +0x18b
github.com/fluxninja/aperture/v2/pkg/notifiers.(*keyTracker).addKeyNotifier(0xc000846e10, {0x4d944d0, 0xc000846f00})
	/src/pkg/notifiers/tracker.go:66 +0x1ff
github.com/fluxninja/aperture/v2/pkg/notifiers.(*DefaultTrackers).writeEvent(0xc000eb9320, 0xc000846e10, {{0xc00138ee39, 0x4}, {0xc000df4bd0, 0x6e, 0x70}, 0x1})
	/src/pkg/notifiers/tracker.go:365 +0x19a
github.com/fluxninja/aperture/v2/pkg/notifiers.(*DefaultTrackers).Start.func1()
	/src/pkg/notifiers/tracker.go:415 +0x525
github.com/fluxninja/aperture/v2/pkg/panic-handler.(*PanicHandlerRegistry).Go.func1()
	/src/pkg/panic-handler/panic-handler.go:108 +0x7b
created by github.com/fluxninja/aperture/v2/pkg/panic-handler.(*PanicHandlerRegistry).Go
	/src/pkg/panic-handler/panic-handler.go:100 +0x72

```
**What version did you use?**
Version: v2.11.1

**What config did you use?**
Config for generating controller deployment manifest using helm file:
```yaml
controller:
  namespaceScoped: true
  config:
    log:
      level: info
      pretty_console: true
      non_blocking: false
    fluxninja:
      endpoint: ""
      installation_mode: KUBERNETES_DAEMONSET
    prometheus:
      address: "http://flux-promoperator-prometheus:9090"

  livenessProbe:
    enabled: false
  serverCert:
    secretName: "flux-poc-controller-secret"
prometheus:
  enabled: false

```
