### ISSUE TITLE
Requests with different priorities are having same drop rate

### ISSUE THREAD

**Issue by hdkshingala** [fluxninja/aperture#86]
I was running the latency-gradient policy with load test and observed that the drop rate for requests from different workload having different priorities are almost same. Below are 2 scenarios with I checked:

1. Executed the load test with 2 users having different workload config and different priorities in policy but their drop_rate was same:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: classification
  namespace: aperture-system
  labels:
    aperture.tech/validate: "true"
data:
  default.classification.yaml: |
    # Example of Flow Classification rules file, showcasing using "extractors" and raw rego.

    selector:
      service: demo1-demo-app.demoapp.svc.cluster.local
      control_point: { traffic: ingress }

    rules:
      # An example rule using extractor.
      # See following RFC for list of available extractors and their syntax.
      # https://www.notion.so/YAML-classification-policies-extractors-a7f36469fdf14c1bbc79c6ba963680a5#9ae103e0c9034c4aba30228d05d91391
      ua:
        extractor:
          from: request.http.headers.user-agent

      # The same rule using raw rego. Requires specifying rego source code and a query
      also-ua:
        rego:
          source: |
            package my.rego.pkg
            import input.attributes.request.http
            ua = http.headers["user-agent"]
          query: data.my.rego.pkg.ua

      user:
        extractor:
          from: request.http.headers.user
```
```yaml
kind: ConfigMap
metadata:
  name: flowcontrol
  namespace: aperture-system
  labels:
    aperture.tech/validate: "true"
apiVersion: v1
data:
  latency-gradient.yaml: |
    evaluation_interval: "0.5s"
    flux_meters:
      - name: "demo1_latency"
        selector:
          service: "demo1-demo-app.demoapp.svc.cluster.local"
          control_point:
            traffic: "ingress"
    circuit:
      - promql:
          query_string: "sum(increase(demo1_latency_sum[5s]))/sum(increase(demo1_latency_count[5s]))"
          evaluation_interval: "1s"
          out_ports:
            output:
              signal_name: "LATENCY"
      - constant:
          value: "2.0"
          out_ports:
            output:
              signal_name: "EMA_LIMIT_MULTIPLIER"
      - arithmetic_combinator:
          operator: "mul"
          in_ports:
            lhs:
              signal_name: "LATENCY"
            rhs:
              signal_name: "EMA_LIMIT_MULTIPLIER"
          out_ports:
            output:
              signal_name: "MAX_EMA"
      - ema:
          ema_window: "300s"
          warm_up_window: "10s"
          correction_factor_on_max_envelope_violation: "0.95"
          in_ports:
            input:
              signal_name: "LATENCY"
            max_envelope:
              signal_name: "MAX_EMA"
          out_ports:
            output:
              signal_name: "LATENCY_EMA"
      - gradient_controller:
          tolerance: "1.1"
          min_gradient: "0.1"
          max_gradient: "1.0"
          in_ports:
            signal:
              signal_name: "LATENCY"
            setpoint:
              signal_name: "LATENCY_EMA"
            max:
              signal_name: "MAX_CONCURRENCY"
            control_variable:
              signal_name: "ACCEPTED_CONCURRENCY"
            optimize:
              signal_name: "CONCURRENCY_INCREMENT"
          out_ports:
            output:
              signal_name: "DESIRED_CONCURRENCY"
      - arithmetic_combinator:
          operator: "sub"
          in_ports:
            lhs:
              signal_name: "INCOMING_CONCURRENCY"
            rhs:
              signal_name: "DESIRED_CONCURRENCY"
          out_ports:
            output:
              signal_name: "DELTA_CONCURRENCY"
      - arithmetic_combinator:
          operator: "div"
          in_ports:
            lhs:
              signal_name: "DELTA_CONCURRENCY"
            rhs:
              signal_name: "INCOMING_CONCURRENCY"
          out_ports:
            output:
              signal_name: "LSF"
      - concurrency_limiter:
          scheduler:
            selector:
              service: "demo1-demo-app.demoapp.svc.cluster.local"
              control_point:
                traffic: "ingress"
            workload_config:
              label_key: "flow_user"
              auto_tokens: true
              default_workload:
                priority: 20
                timeout: "0.005s"
              workloads:
                - label_value: "A"
                  priority: 50
                  timeout: "0.005s"
                - label_value: "B"
                  priority: 200
                  timeout: "0.005s"
            out_ports:
              accepted_concurrency:
                signal_name: "ACCEPTED_CONCURRENCY"
              incoming_concurrency:
                signal_name: "INCOMING_CONCURRENCY"
          load_shed_actuator:
            in_ports:
              load_shed_factor:
                signal_name: "LSF"
      - constant:
          value: "2.0"
          out_ports:
            output:
              signal_name: "CONCURRENCY_LIMIT_MULTIPLIER"
      - constant:
          value: "10.0"
          out_ports:
            output:
              signal_name: "MIN_CONCURRENCY"
      - constant:
          value: "5.0"
          out_ports:
            output:
              signal_name: "LINEAR_CONCURRENCY_INCREMENT"
      - arithmetic_combinator:
          operator: "mul"
          in_ports:
            lhs:
              signal_name: "CONCURRENCY_LIMIT_MULTIPLIER"
            rhs:
              signal_name: "ACCEPTED_CONCURRENCY"
          out_ports:
            output:
              signal_name: "UPPER_CONCURRENCY_LIMIT"
      - max:
          in_ports:
            inputs:
              - signal_name: "UPPER_CONCURRENCY_LIMIT"
              - signal_name: "MIN_CONCURRENCY"
          out_ports:
            output:
              signal_name: "MAX_CONCURRENCY"
      - sqrt:
          scale: "0.5"
          in_ports:
            input:
              signal_name: "ACCEPTED_CONCURRENCY"
          out_ports:
            output:
              signal_name: "SQRT_CONCURRENCY_INCREMENT"
      - arithmetic_combinator:
          operator: "add"
          in_ports:
            lhs:
              signal_name: "LINEAR_CONCURRENCY_INCREMENT"
            rhs:
              signal_name: "SQRT_CONCURRENCY_INCREMENT"
          out_ports:
            output:
              signal_name: "CONCURRENCY_INCREMENT_NORMAL"
      - constant:
          value: "1.2"
          out_ports:
            output:
              signal_name: "OVERLOAD_MULTIPLIER"
      - arithmetic_combinator:
          operator: "mul"
          in_ports:
            lhs:
              signal_name: "LATENCY_EMA"
            rhs:
              signal_name: "OVERLOAD_MULTIPLIER"
          out_ports:
            output:
              signal_name: "LATENCY_OVERLOAD"
      - constant:
          value: "10.0"
          out_ports:
            output:
              signal_name: "CONCURRENCY_INCREMENT_OVERLOAD"
      - decider:
          operator: "gt"
          in_ports:
            lhs:
              signal_name: "LATENCY"
            rhs:
              signal_name: "LATENCY_OVERLOAD"
            on_true:
              signal_name: "CONCURRENCY_INCREMENT_OVERLOAD"
            on_false:
              signal_name: "CONCURRENCY_INCREMENT_NORMAL"
          out_ports:
            output:
              signal_name: "CONCURRENCY_INCREMENT"
```
```javascript
import http from "k6/http";
import { check } from "k6";

export let options = {
  discardResponseBodies: true,
  scenarios: {
    userA: {
      executor: "ramping-vus",
      stages: [
        { duration: "30s", target: 5 }, // simulate ramp-up of traffic from 0 to 5 users over 30 seconds
        { duration: "2m", target: 5 }, // stay at 5 users for 2 minutes
        { duration: "30s", target: 60 }, // ramp-up to 60 users over 30 seconds
        { duration: "4m", target: 60 }, // stay at 60 users for 4 minutes (peak hour)
        { duration: "1m", target: 0 }, // ramp-down to 0 users in 1 minute
      ],
      env: { USER: "A" },
    },
    userB: {
      executor: "ramping-vus",
      stages: [
        { duration: "30s", target: 5 }, // simulate ramp-up of traffic from 0 to 5 users over 30 seconds
        { duration: "2m", target: 5 }, // stay at 5 users for 2 minutes
        { duration: "30s", target: 60 }, // ramp-up to 60 users over 30 seconds
        { duration: "4m", target: 60 }, // stay at 60 users for 4 minutes (peak hour)
        { duration: "1m", target: 0 }, // ramp-down to 0 users in 1 minute
      ],
      env: { USER: "B" },
    },
  },
};

export default function () {
  let user = __ENV.USER;
  const url = "http://demo1-demo-app.demoapp.svc.cluster.local/request";
  const headers = {
    "Content-Type": "application/json",
    Cookie:
      "session=eyJ1c2VyIjoia2Vub2JpIn0.YbsY4Q.kTaKRTyOIfVlIbNB48d9YH6Q0wo",
    User: user,
  };
  const body = {};
  let res = http.request("POST", url, JSON.stringify(body), {
    headers: headers,
  });
  check(res, {
    "http status was 200": res.status === 200,
  });
}
```
Below is the result from druid:
![image](https://user-images.githubusercontent.com/34568645/183834545-5a0cd72d-50c3-4645-924f-02e35e17966c.png)

2. In this case, I have added a new user and used the same policy and classification as above. Here also, the drop rates were almost similar for different priority loads.

Below is the load-test.js for this scenario:
```javascript
import http from "k6/http";
import { check } from "k6";

export let options = {
  discardResponseBodies: true,
  scenarios: {
    userA: {
      executor: "ramping-vus",
      stages: [
        { duration: "30s", target: 5 }, // simulate ramp-up of traffic from 0 to 5 users over 30 seconds
        { duration: "2m", target: 5 }, // stay at 5 users for 2 minutes
        { duration: "30s", target: 60 }, // ramp-up to 60 users over 30 seconds
        { duration: "4m", target: 60 }, // stay at 60 users for 4 minutes (peak hour)
        { duration: "1m", target: 0 }, // ramp-down to 0 users in 1 minute
      ],
      env: { USER: "A" },
    },
    userB: {
      executor: "ramping-vus",
      stages: [
        { duration: "30s", target: 5 }, // simulate ramp-up of traffic from 0 to 5 users over 30 seconds
        { duration: "2m", target: 5 }, // stay at 5 users for 2 minutes
        { duration: "30s", target: 60 }, // ramp-up to 60 users over 30 seconds
        { duration: "4m", target: 60 }, // stay at 60 users for 4 minutes (peak hour)
        { duration: "1m", target: 0 }, // ramp-down to 0 users in 1 minute
      ],
      env: { USER: "B" },
    },
    userC: {
      executor: "ramping-vus",
      stages: [
        { duration: "30s", target: 5 }, // simulate ramp-up of traffic from 0 to 5 users over 30 seconds
        { duration: "2m", target: 5 }, // stay at 5 users for 2 minutes
        { duration: "30s", target: 60 }, // ramp-up to 60 users over 30 seconds
        { duration: "4m", target: 60 }, // stay at 60 users for 4 minutes (peak hour)
        { duration: "1m", target: 0 }, // ramp-down to 0 users in 1 minute
      ],
      env: { USER: "C" },
    },
  },
};

export default function () {
  let user = __ENV.USER;
  const url = "http://demo1-demo-app.demoapp.svc.cluster.local/request";
  const headers = {
    "Content-Type": "application/json",
    Cookie:
      "session=eyJ1c2VyIjoia2Vub2JpIn0.YbsY4Q.kTaKRTyOIfVlIbNB48d9YH6Q0wo",
    User: user,
  };
  const body = {};
  let res = http.request("POST", url, JSON.stringify(body), {
    headers: headers,
  });
  check(res, {
    "http status was 200": res.status === 200,
  });
}
```

Below is the result from druid:
![image](https://user-images.githubusercontent.com/34568645/183835001-fc5ee39d-2651-4fad-9000-a8bcf0c2bc85.png)

As we have different priorities for different users, the drop rate shouldn't be same and should be much lower for higher priority loads.
