### ISSUE TITLE
Incorrect request drop rate with rate limiter policy

### ISSUE THREAD

**Issue by hdkshingala** [fluxninja/aperture#87]
I tried to run the rate limiter policy with different scenarios as below but the request decisions where not as expected.

1. I used the below rate limiter policy where I changed the limit value to 100 requests/minute per user based on the user header but the drop rate is very high and very few requests got accepted.
```yaml
kind: ConfigMap
metadata:
  name: flowcontrol
  namespace: aperture-system
  labels:
    aperture.tech/validate: "true"
apiVersion: v1
data:
  rate-limit-policy.yaml: |
    evaluation_interval: "0.5s"
    circuit:
      - constant:
          value: "100.0"
          out_ports:
            output:
              signal_name: "RATE_LIMIT"
      - rate_limiter:
          in_ports:
            limit:
              signal_name: "RATE_LIMIT"
          selector:
            service: "demo1-demo-app.demoapp.svc.cluster.local"
            control_point:
              traffic: "ingress"
          label_key: "request_header_user"
          limit_reset_interval: "60s"
```
I have used the same load-test.js using K6 available on [main](https://github.com/fluxninja/cloud/blob/main/services/tools/load_generator/scenarios/load_test.js) and tilt under demoapp1 pod.

Below is the output from Druid:
![image](https://user-images.githubusercontent.com/34568645/183909969-0e5f7a05-afdf-4c08-9330-9c90cb223d2b.png)

2. In this scenario, I have configured the classification for demoapp using the example available on [main](https://github.com/fluxninja/aperture/blob/main/example-classification-cm-demoapp.yaml) and changed the policy as below:

```yaml
kind: ConfigMap
metadata:
  name: flowcontrol
  namespace: aperture-system
  labels:
    aperture.tech/validate: "true"
apiVersion: v1
data:
  rate-limit-policy.yaml: |
    evaluation_interval: "0.5s"
    circuit:
      - constant:
          value: "100.0"
          out_ports:
            output:
              signal_name: "RATE_LIMIT"
      - rate_limiter:
          in_ports:
            limit:
              signal_name: "RATE_LIMIT"
          selector:
            service: "demo1-demo-app.demoapp.svc.cluster.local"
            control_point:
              traffic: "ingress"
          label_key: "request_header_flow_user"
          limit_reset_interval: "60s"
```

In this case, all the requests got accepted and none got dropped, which I feel is also not correct as I tried different values like 10, 50 etc and still it was accepting all. I tried `flow_user` as value for `label_key` and that too had same output.
